version: '3.3'

services:

  postgres:
    restart: always
    image: postgres:latest
    build:
      context: ./Docker_db
      dockerfile: db.Dockerfile
    environment:
      POSTGRES_USER: "admin"
      POSTGRES_DB: "cargilldbdev"
      POSTGRES_HOST_AUTH_METHOD: "trust"
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5434:5434"

volumes:
  db-data: